routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Support\Facades\Route;

use http\Env\Request;

Route::get('/', function () {
    return view('welcome');
});


Route::get('user/login', function () {
    return view('user.login');
});


Route::get('user/home', function () {
    return view('user.home');
});

Route::get('/admin/home', function () {
    return view('admin.home');
});


//Auth::routes();

Route::get('user/home', 'User\UserHomeController@index')->name('user.home');
Route::get('admin/home', 'Admin\AdminHomeController@index')->name('admin.home');


// Authentication Routes...USER
Route::get('user/login', 'User\Auth\LoginController@showLoginForm')->name('user.login');
Route::post('user/login', 'User\Auth\LoginController@login');
Route::post('logout', 'User\Auth\LoginController@logout')->name('logout');


// Registration Routes...
Route::get('user/register', 'User\Auth\RegisterController@showRegistrationForm')->name('user.register');
Route::post('user/register', 'User\Auth\RegisterController@register');



// Authentication Routes...ADMIN
Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\LoginController@login');
Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');


// Registration Routes...
if ($options['register'] ?? true) {
    Route::get('admin/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('admin/register', 'Admin\Auth\RegisterController@register');
}
/*
// Password Reset Routes...
if ($options['reset'] ?? true) {
    Route::resetPassword();
}

// Email Verification Routes...
if ($options['verify'] ?? false) {
        Route::emailVerification();
}
*/

Route::resource('user/product', 'User\Product\ProductController')->middleware('auth:user');

Route::resource('admin/category', 'Admin\Category\CategoryController')->middleware('auth:admin');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'description', 'category_id', 'price', 'expire_at',
    ];


    public function category()
    {
       return $this->belongsTo('App\Models\Category') ;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'name', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/Product/ProductController.php
<?php

namespace App\Http\Controllers\User\Product;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // $products = Product::all()->sortBy('id');
        $products = Product::with('category')->get();

        return view('user.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('user.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required', 'string', 'min:3', 'max:55', 'unique:products'],
            'description' => ['nullable', 'string', 'min:5'],
            'category_id' => ['required', 'int'],
            'price' => ['required', 'int'],
            'expire_at' => ['required', 'date', 'after:'.date('d-m-Y')],
        ]);

        Product::create([
            'name'=>$request->name,
            'description'=>$request->description,
            'category_id'=>$request->category_id,
            'price'=>$request->price,
            'expire_at'=>$request->expire_at
        ]);

        return redirect(route('product.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view('user.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $product = Product::findOrFail($id);

        return view('user.product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => ['required', 'string', 'min:3', 'max:55', Rule::unique('products')->ignore($id)],
            'description' => ['nullable', 'string', 'min:5'],
            'category_id' => ['required', 'int'],
            'price' => ['required', 'int'],
            'expire_at' => ['required', 'date', 'after_or_equal:'.date('d-m-Y')],
        ]);

        Product::findOrFail($id)->update([
            'name'=>$request->name,
            'description'=>$request->description,
            'category_id'=>$request->category_id,
            'price'=>$request->price,
            'expire_at'=>$request->expire_at
        ]);
        return redirect(route('product.show', $id));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);

        return redirect(route('product.index'));
    }
}

app/Http/Controllers/User/UserHomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;

class UserHomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:user');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('user.home');
    }
}

resources/views/user/product/create.blade.php
@extends('user.product.layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create product') }} <a class="btn btn-primary float-right" href="{{route('user.home')}}">#Cancel</a></div>

                <div class="card-body">
                    <form method="POST" action="{{ route('product.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" placeholder="Decrivez la categorie ici..." type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description" autofocus>
                                </textarea>
                                @error('description')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="category_id" class="col-md-4 col-form-label text-md-right">{{ __('Category') }}</label>

                            <div class="col-md-6">
                                <select class="form-control" name="category_id">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>

                                @error('category_id')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="number" min="0" step="1" form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}" required autocomplete="price" autofocus>

                                @error('price')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="expiration" class="col-md-4 col-form-label text-md-right">{{ __('Expiration date') }}</label>

                            <div class="col-md-6">
                                <input id="expiration" type="date" class="form-control @error('expire_at') is-invalid @enderror" name="expire_at" value="{{ old('expire_at') }}" required autocomplete="expire_at" autofocus>

                                @error('expire_at')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/product/edit.blade.php
@extends('user.product.layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Update product - ') }}<strong style="color: darkred"> #{{$product->id}}</strong>
                        <a class="btn btn-primary float-right" href="{{route('product.show', $product)}}">Cancel</a></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('product.update', $product) }}">
                            {{method_field('PUT')}}
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input autocomplete="name" autofocus
                                           class="form-control @error('name') is-invalid @enderror"
                                           id="name" name="name"
                                           placeholder="Nouveau nom..." required type="text"
                                           value="{{ old('name') ?: $product->name }}">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right" for="description">{{ __('Description') }}</label>

                                <div class="col-md-6">
                                <textarea autocomplete="description" autofocus
                                          class="form-control @error('description') is-invalid @enderror"
                                          id="description"
                                          name="description" placeholder="Nouvelle description..." required
                                          type="text"> {{ old('description') ?: $product->description }}
                                </textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right" for="category_id">{{ __('Category') }}</label>

                                <div class="col-md-6">
                                    <select class="form-control" name="category_id">
                                        @foreach($categories as $category)
                                            <option  value="{{$category->id}}" selected>
                                                {{($product->category_id == $category->id) ? $category->name : $category->name}}
                                            </option>
                                        @endforeach
                                    </select>

                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                                <div class="col-md-6">
                                    <input form-control id="price" @error('price') is-invalid min="0"
                                           placeholder="New price..."
                                           step="1" type="number" @enderror name="price" value="{{ old('price') ?: $product->price }}" required autocomplete="price" autofocus>

                                    @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="expire_at" class="col-md-4 col-form-label text-md-right">{{ __('Expiration date') }}</label>

                                <div class="col-md-6">
                                    <input autocomplete="expire_at" autofocus
                                           class="form-control @error('expire_at') is-invalid @enderror"
                                           id="expire_at" name="expire_at"
                                           required type="date" value="{{ old('expire_at') ?: $product->expire_at }}">

                                    @error('expire_at')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-success">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/product/index.blade.php
@extends('user.product.layouts.app')
@section('content')
    <div class="m-lg-3">
    <h1>Products</h1>
    <p><a href="{{route('product.create')}}" class="btn btn-primary">New product</a></p><br>
    @if(count($products)>0)
        <table class="table table-bordered table-striped table-sm">
            <thead class="thead-dark">
            <tr>
                <th class="col-sm-1">ID</th>
                <th class="col-sm-1">Nom</th>
                <th class="col-sm-3">Description</th>
                <th class="col-sm-1">Category</th>
                <th class="col-sm-1">Price</th>
                <th class="col-sm-1">Expiration date</th>
            </tr>
            </thead>
            @foreach($products as $product)
            <tr>
                <td><a href="{{route('product.show', $product->id)}}">{{ $product->id }}</a></td>
                <td><a href="{{route('product.show', $product->id)}}">{{ $product->name }}</a></td>
                <td>{{ $product->description }}</td>
                <td>{{ $product->category->name }}</td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->expire_at }}</td>
            </tr>
            @endforeach
        </table>
    @else
        <strong>No products</strong>
    @endif
    </div>

@endsection

resources/views/user/product/show.blade.php
@extends('user.product.layouts.app')

@section('content')
    <div class="m-lg-3">
    <h1>{{$product->name}}</h1>

    <p><strong>{{$product->description}}</strong></p>

    <a class="btn btn-primary" href="{{route('product.index')}}">See all products</a> |
    <a class="btn btn-primary" href="{{route('product.edit', $product->id)}}">Update</a> |

    <form action="{{route('product.destroy', $product->id)}}" method="POST" class="d-inline-block">
        {{csrf_field()}}
        {{method_field("DELETE")}}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
    </div>

@endsection